config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'ask', to: 'questions#ask'
  get 'answer', to: 'questions#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    @question = params["question"]
    if @question.include?("hello")
       @answer = "I don't care, get dressed and go to work!"
    elsif @question.include?("shopping")
      @answer = "Silly question, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="title">
<h1>Stupid Coaching</h1>
</div>
<div class="question">
<h3><%= @question %></h3>
<p>-You</p>
</div>
<div class="Answer">
<h3><%= @answer%></h3>
<p>-coach</p>
</div>
<div class="link">
  <%= link_to("Ask a new question", ask_path)%>
</div>

app/views/questions/ask.html.erb
<div class="container">
<h1>Stupid Coaching</h1>
<p>Ask your coach anything:</p>
  <form action="/answer" data-turbo="false">
   <div class="input-group mb-3">
     <input class="form-control" type="text" placeholder="ask" name="question">
     <%# <input type="submit" value="Ask!" class="btn btn-primary"> %>
     <button class="btn btn-primary" type="submit-addon2">Ask!</button>
   </div>
  </form>
</div>
</div>